name: Automatic Release

on:
  push:
    tags:
      - 'v*'  # Se activa cuando se realiza un push de una etiqueta que comienza con "v"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}  # Usa el nombre de la etiqueta como el tag de la release
        release_name: Release ${{ github.ref_name }}  # Usa el nombre de la etiqueta como título
        draft: false  # Publica la release directamente
        prerelease: false  # Cambia a true si la release es pre-lanzamiento

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./path/to/your/asset.zip  # Cambia esto por la ruta a tu archivo
        asset_name: asset.zip  # Cambia el nombre del archivo como quieras
        asset_content_type: application/zip
